### ISSUE TITLE
to_string fpermissive error

### ISSUE THREAD

**Issue by jojo2massol** [trungams/http-server#1]
I just got this error while trying to make:
![image](https://user-images.githubusercontent.com/54369031/179845304-997d2ad9-df8c-4196-83bc-dd6e3dff7f40.png)

In file included from /home/pi/http-server/test/main.cc:10:
/home/pi/http-server/src/http_message.h:150:22: error: friend declaration of ‘std::string to_string(const simple_http_server::HttpResponse&, bool)’ specifies default arguments and isn’t a definition [-fpermissive]
  150 |   friend std::string to_string(const HttpResponse& request, bool send_content = true);
      |                      ^~~~~~~~~
/home/pi/http-server/src/http_message.h:159:13: error: friend declaration of ‘std::string simple_http_server::to_string(const simple_http_server::HttpResponse&, bool)’ specifies default arguments and isn’t the only declaration [-fpermissive]
  159 | std::string to_string(const HttpResponse& response, bool send_content);
      |             ^~~~~~~~~
/home/pi/http-server/src/http_message.h:150:22: note: previous declaration of ‘std::string simple_http_server::to_string(const simple_http_server::HttpResponse&, bool)’
  150 |   friend std::string to_string(const HttpResponse& request, bool send_content = true);
      |                      ^~~~~~~~~
make[2]: *** [CMakeFiles/test_SimpleHttpServer.dir/build.make:82: CMakeFiles/test_SimpleHttpServer.dir/test/main.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/test_SimpleHttpServer.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by trungams** [comment]
Wow thank you for letting me know. Not sure why I never saw this message before. I fixed it along with reformatting the source code, so it might be confusing to see where the fix is. But if you are interested, you can read more about it here: https://stackoverflow.com/questions/22533511/friend-declaration-specifying-a-default-argument-must-be-a-definition.

I had to move the default argument from the function inside HttpResponse definition to the function below on line 159. Just pull the latest change and it should work.
